name: autorebase

on:
  # Run on every push to any branch (not a tag).
  push:
    branches:
      - "**"

  # Run when a pull request gets labeled.  Note that the workflow runs from the
  # base branch of the PR in this case, because `pull_request_target` is used
  # instead of `pull_request`.
  pull_request_target:
    types:
      - labeled

jobs:
  autorebase:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        env:
          context_github: ${{ toJSON(github) }}
        run: true

      - id: token
        name: Generate a GitHub token
        uses: tibdex/github-app-token@v1.5.2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: rebase
        name: Rebase the eligible PRs
        uses: peter-evans/rebase@v2.0.0
        with:
          token: ${{ steps.token.outputs.token }}
          include-labels: "autorebase:opt-in"
          base: ${{ github.ref_name }}
