name: Automatic flake update
on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Generate matrix from flake inputs
        id: generate_matrix
        run: |
          set -euo pipefail
          matrix="$(nix flake metadata --json | jq -rcM '.locks.nodes.root.inputs | {input: keys}')"
          echo "::set-output name=matrix::$matrix"

  update_input:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    env:
      automerge: ${{ matrix.input == 'nixpkgs' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Generate a GitHub token
        id: generate-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update ${{ matrix.input }}
        uses: cpcloud/flake-update-action@v1.0.4
        with:
          dependency: ${{ matrix.input }}
          pull-request-token: ${{ steps.generate-token.outputs.token }}
          pull-request-author: "sigprof[bot] <sigprof[bot]@users.noreply.github.com>"
          pull-request-labels: "dependencies, autorebase:opt-in"
          delete-branch: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-branch-prefix: automatic-flake-update/
          automerge: ${{ env.automerge }}
