name: autorebase

on:
  # Run when a pull request gets labeled.  Note that the workflow runs from the
  # base branch of the PR in this case, because `pull_request_target` is used
  # instead of `pull_request`.
  pull_request_target:
    types:
      - labeled

  # Run when the `CI` workflow run is requested.  This roundabout way is used
  # to hide the `autorebase` workflow from the list of checks, at the cost of
  # losing the possibility to autorebase PRs to branches that are not checked
  # by CI on every push.
  workflow_run:
    types:
      - requested
    workflows:
      - CI

jobs:
  autorebase:
    runs-on: ubuntu-latest
    if: >-
      (
        (github.event_name == 'pull_request_target')
        && (github.event.action == 'labeled')
        && (github.event.label.name == 'autorebase:opt-in')
      )
      || (
        (github.event_name == 'workflow_run')
      )
    steps:
      - id: token
        name: Generate a GitHub token
        uses: tibdex/github-app-token@v2.0.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: rebase
        name: Rebase the eligible PRs
        uses: peter-evans/rebase@v2.0.1
        with:
          token: ${{ steps.token.outputs.token }}
          include-labels: "autorebase:opt-in"
