name: autorebase

on:
  # Run when a pull request gets labeled.  Note that the workflow runs from the
  # base branch of the PR in this case, because `pull_request_target` is used
  # instead of `pull_request`.
  pull_request_target:
    types:
      - labeled

  # Run when the `CI` workflow run is requested.  This roundabout way is used
  # to hide the `autorebase` workflow from the list of checks.
  workflow_run:
    types:
      - requested
    workflows:
      - CI

jobs:
  autorebase:
    runs-on: ubuntu-latest
    if: >-
      ${{
        (
          (github.event_name == 'push')
          && (github.ref_type == 'branch')
        )
        || (
          (github.event_name == 'pull_request_target')
          && (github.event.action == 'labeled')
          && (github.event.label.name == 'autorebase:opt-in')
        )
        || (
          (github.event_name == 'workflow_run')
        )
      }}
    steps:
      - id: debug
        name: Debug
        env:
          github_context: ${{ toJSON(github) }}
        run: true

      - id: token
        if: false
        name: Generate a GitHub token
        uses: tibdex/github-app-token@v1.5.2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: rebase
        name: Rebase the eligible PRs
        if: false
        uses: peter-evans/rebase@v2.0.0
        with:
          token: ${{ steps.token.outputs.token }}
          include-labels: "autorebase:opt-in"
          base: ${{ github.ref_name }}
