name: Automatic flake update
on:
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dependency:
          - nixpkgs
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Generate a GitHub token
        id: generate-token
        uses: tibdex/github-app-token@v1.5.2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update ${{ matrix.dependency }}
        uses: cpcloud/flake-update-action@v1.0.2
        with:
          dependency: ${{ matrix.dependency }}
          pull-request-token: ${{ steps.generate-token.outputs.token }}
          pull-request-author: "sigprof[bot] <sigprof[bot]@users.noreply.github.com>"
          pull-request-labels: dependencies
          delete-branch: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-branch-prefix: automatic-flake-update/
          automerge: true
