name: CI Arch
on:
  workflow_call:
    inputs:
      system:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      matrix:
        required: true
        type: string

jobs:
  flake:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).flake }}
    steps:
      - run: |
          echo "Building ${{ matrix.check }}"

  nur:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).nur }}
    steps:
      - run: |
          echo "Building ${{ matrix.check }} on ${{ matrix.channel }}"

  nur-main:
    needs:
      - flake
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).nur-main }}
    steps:
      - run: |
          echo "Building ${{ matrix.check }} on ${{ matrix.channel }}"

  flake-hosts:
    needs:
      - flake
    runs-on: ${{ inputs.runs-on }}
    if: fromJSON(inputs.matrix).flake-hosts
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).flake-hosts }}
    steps:
      - run: |
          echo "Building ${{ matrix.check }}"
