name: CI Arch
on:
  workflow_call:
    inputs:
      system:
        required: true
        type: string
      runs-on:
        required: true
        type: string

jobs:
  flake-packages:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        check:
          - pkg1
          - pkg2
          - pkg3
    steps:
      - run: |
          echo "Building ${{ matrix.check }}"

  flake-hosts:
    needs:
      - flake-packages
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        check:
          - host-1
          - host-2
          - host-3
    steps:
      - run: |
          echo "Building ${{ matrix.check }}"

  nur-main:
    needs:
      - flake-packages
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        check:
          - pkg1
          - pkg2
          - pkg3
        channel:
          - nixos-22.05
    steps:
      - run: |
          echo "Building ${{ matrix.check }} on ${{ matrix.channel }}"

  nur-other:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        check:
          - pkg1
          - pkg2
          - pkg3
        channel:
          - nixos-21.11
          - nixos-unstable
          - nixpkgs-unstable
    steps:
      - run: |
          echo "Building ${{ matrix.check }} on ${{ matrix.channel }}"
