name: CI Full
on:
  workflow_dispatch:
    inputs:
      flake_only:
        description: 'Run flake tests only'
        default: false
        type: boolean

jobs:
  x86_64-linux:
    uses: ./.github/workflows/ci-arch.yml
    with:
      system: x86_64-linux
      runs-on: ubuntu-latest
    secrets: inherit