name: CI per system
on:
  workflow_call:
    inputs:
      system:
        required: true
        type: string
        description: >
          System name in the format used by Nix (e.g., `x86_64-linux`).
      runs-on:
        required: true
        type: string
        description: >
          GitHub machine type to be used for the build (e.g., `ubuntu-latest`).
          Needs to be compatible with the specified value of `system`.
      matrix:
        required: true
        type: string
        description: >
          The description of Nix derivations to be built in the JSON format.
          Should contain only derivations for the system type specified in
          `system` which are buildable on a machine specified in `runs-on`.

jobs:
  early-checks:
    runs-on: ${{ inputs.runs-on }}
    if: fromJSON(inputs.matrix).flake.earlyChecks.item[0]
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).flake.earlyChecks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build
        uses: ./.github/actions/nix-build
        with:
          item: ${{ toJSON(matrix.item) }}
          system: ${{ inputs.system }}
          cachix-name: sigprof
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  pkgs:
    runs-on: ${{ inputs.runs-on }}
    if: fromJSON(inputs.matrix).flake.packages.item[0]
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).flake.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build
        uses: ./.github/actions/nix-build
        with:
          item: ${{ toJSON(matrix.item) }}
          system: ${{ inputs.system }}
          cachix-name: sigprof
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  nur:
    runs-on: ${{ inputs.runs-on }}
    if: fromJSON(inputs.matrix).nur.other.include[0]
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).nur.other }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build
        uses: ./.github/actions/nix-build
        with:
          item: ${{ toJSON(matrix.item) }}
          system: ${{ inputs.system }}
          channel: ${{ matrix.channel }}
          cachix-name: sigprof
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  nur1:
    runs-on: ${{ inputs.runs-on }}
    if: fromJSON(inputs.matrix).nur.stage1.include[0]
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).nur.stage1 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build
        uses: ./.github/actions/nix-build
        with:
          item: ${{ toJSON(matrix.item) }}
          system: ${{ inputs.system }}
          channel: ${{ matrix.channel }}
          cachix-name: sigprof
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  nur2:
    needs:
      - pkgs
    runs-on: ${{ inputs.runs-on }}
    if: >
      always() &&
      (needs.pkgs.result == 'success' || needs.pkgs.result == 'skipped') &&
      fromJSON(inputs.matrix).nur.stage2.include[0]
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).nur.stage2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build
        uses: ./.github/actions/nix-build
        with:
          item: ${{ toJSON(matrix.item) }}
          system: ${{ inputs.system }}
          channel: ${{ matrix.channel }}
          cachix-name: sigprof
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  nur3:
    needs:
      - nur1
    runs-on: ${{ inputs.runs-on }}
    if: >
      always() &&
      (needs.nur1.result == 'success' || needs.nur1.result == 'skipped') &&
      fromJSON(inputs.matrix).nur.stage3.include[0]
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).nur.stage3 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build
        uses: ./.github/actions/nix-build
        with:
          item: ${{ toJSON(matrix.item) }}
          system: ${{ inputs.system }}
          channel: ${{ matrix.channel }}
          cachix-name: sigprof
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  hosts:
    needs:
      - pkgs
    runs-on: ${{ inputs.runs-on }}
    if: >
      always() &&
      (needs.pkgs.result == 'success' || needs.pkgs.result == 'skipped') &&
      fromJSON(inputs.matrix).flake.hosts.item[0]
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).flake.hosts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build
        uses: ./.github/actions/nix-build
        with:
          item: ${{ toJSON(matrix.item) }}
          system: ${{ inputs.system }}
          cachix-name: sigprof
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  checks:
    needs:
      - pkgs
    runs-on: ${{ inputs.runs-on }}
    if: >
      always() &&
      (needs.pkgs.result == 'success' || needs.pkgs.result == 'skipped') &&
      fromJSON(inputs.matrix).flake.checks.item[0]
    strategy:
      matrix: ${{ fromJSON(inputs.matrix).flake.checks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Build
        uses: ./.github/actions/nix-build
        with:
          item: ${{ toJSON(matrix.item) }}
          system: ${{ inputs.system }}
          cachix-name: sigprof
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
