name: CI Test
on:
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      mode:
        description: 'Test mode: quick|default|full'
        required: true
        default: "default"

env:
  TEST_MODE: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.mode) || 'default' }}
  TEST_MATRIX:
    os:
      - ubuntu-latest
      - macos-latest

jobs:
  dump:
    name: Dump
    runs-on: ubuntu-latest
    steps:
      - name: Report data
        run: |
          printf 'TEST_MODE="%s"\n' "$TEST_MODE"
          printf 'TEST_MATRIX="%s"\n' "$TEST_MATRIX"

  #build:
  #  name: Build
  #  needs: dump
  #  strategy:
  #    fail-fast: ${{ !(env.TEST_MODE == 'full') }}
  #    matrix:
  #      os:
  #        - ubuntu-latest
  #        - macos-latest
  #  runs-on: ${{ matrix.os }}
  #  steps:
  #    - name: Fail
  #      run: |
  #        false
