name: dump-contexts
on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item:
          - item_1
          - item_2
    steps:
      - name: Try to find my run ID
        run: |
          # Try to find my run ID
          curl -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            '${{github.api_url}}/repos/${{github.repository}}/commits/${{github.sha}}/check-runs?status=in_progress&check_name=Dump%20(${{matrix.item}})'

      - name: Dump JSON contexts
        env:
          github: ${{ toJSON(github) }}
          strategy: ${{ toJSON(strategy) }}
          matrix: ${{ toJSON(matrix) }}
          job: ${{ toJSON(job) }}
          runner: ${{ toJSON(runner) }}
          env: ${{ toJSON(env) }}
        run: |
          # Dump JSON contexts
          for var in github strategy matrix job runner env; do
            echo "::group::$var"
            jq -n "env.${var} | fromjson"
            echo "::endgroup::"
          done

      - name: Dump shell environment
        run: set
