name: Matrix Results
on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        env:
          DATA: |
            {
              "os": ["ubuntu-latest", "macos-latest"],
              "node-version": ["14", "16"]
            }
        run: |
          jq -rn 'env.DATA | fromjson | @json "::set-output name=matrix::\(.)"'

  build:
    needs:
      - setup
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    outputs:
      output_${{strategy.job-index}}: ${{steps.step1.outputs.output}}
    runs-on: ubuntu-latest
    steps:
      - id: step1
        name: Pretend we are doing something
        run: |
          output='${{matrix.os}}:${{matrix.node-version}}'
          echo '::set-output name=output::$output'

  summarize:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - id: collect
        env:
          OUTPUTS: ${{ toJSON(needs.build.outputs) }}
        run: |
          jq -n 'env.OUTPUTS | fromjson'
