name: rebase-command
on:
  repository_dispatch:
    types:
      - rebase-command

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub token
        id: token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Rebase the PR
        uses: peter-evans/rebase@v2.0.0
        id: rebase
        with:
          head: ${{ github.event.client_payload.pull_request.head.label }}
          token: ${{ steps.token.outputs.token }}

      - name: Add reaction
        if: steps.rebase.outputs.rebased-count == 1
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          token: ${{ steps.token.outputs.token }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
