name: Test2
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        nix:
          - channel: nixos-22.05
            flake: flake
          - channel: nixos-unstable
          - channel: nixpkgs-unstable
        os:
          - system: x86_64-linux
            runs_on: ubuntu-latest
          - system: x86_64-darwin
            runs_on: macos-latest
    runs-on: ${{ matrix.os.runs_on }}
    if: matrix.nix.flake
    steps:
      - name: Report matrix value
        env:
          DATA: ${{ toJSON(matrix) }}
        run: |
          printf '%s' "$DATA" | jq
      - name: Flake tests
        if: matrix.nix.flake
        run: |
          echo "Running flake tests..."
      - name: Set NIX_PATH for non-flake tests
        run: |
          echo "NIX_PATH=nixpkgs=channel:${{matrix.nix.channel}}" >> "$GITHUB_ENV"
      - name: Non-flake tests
        run: |
          echo "Running non-flake tests..."

