name: Test2
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - system: x86_64-linux
            runs_on: ubuntu-latest
          - system: x86_64-darwin
            runs_on: macos-latest
        include:
          - channel: nixos-22.05
          - channel: nixos-unstable
          - flake: true
    runs-on: ubuntu-latest
    steps:
      - name: Report matrix value
        env:
          DATA: ${{ toJSON(matrix) }}
        run: |
          printf '%s' "$DATA" | jq
