name: Test
on:
  workflow_dispatch:
    inputs:
      matrixOverride:
        description: >
          Matrix override for the manual workflow run.  Specify a JSON value
          which overrides the `source`, `nixPath` and `os` keys as desired.
          Unspecified keys will inherit the sets of values from the default
          matrix.
        required: false

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.result }}
    steps:
      - id: parse
        name: Parse workflow inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/github-script@v4.0.2
        with:
          script: |
            const payload = context.payload;
            const inputs = payload && payload.inputs;
            const matrixOverrideStr = inputs && inputs.matrixOverride && inputs.matrixOverride.trim();
            let matrixOverride = {};
            if (matrixOverrideStr) {
              const params = matrixOverrideStr.split(/\s*;\s*/);
              for (param of params) {
                const nameAndValue = param.match(/^([^=\s]+)\s*=\s*(.*)$/);
                if (!nameAndValue[1] || !nameAndValue[2]) {
                  console.error(`Invalid matrix value "${param}"`);
                  throw "Invalid workflow parameter";
                }
                const name = nameAndValue[1];
                if (matrixOverride[name]) {
                  console.error(`Duplicate matrix key "${name}"`);
                  throw "Invalid workflow parameter";
                }
                const values = nameAndValue[2].split(/\s*,\s*/);
                matrixOverride[name] = values;
              }
              console.log("Matrix override:", matrixOverride);
            } else {
              console.log("No matrix override specified.");
              matrixOverride = null;
            }
            return matrixOverride;

      - id: matrix
        name: Prepare the matrix
        uses: actions/github-script@v4.0.2
        env:
          MATRIX_OVERRIDE: ${{ steps.parse.outputs.result }}
        with:
          script: |
            const defaultMatrix = {
              source: [
                { repo: "qmk/qmk_firmware", ref: "master"  },
                { repo: "qmk/qmk_firmware", ref: "develop" },
              ],
              nixPath: [ "nixpkgs=channel:nixos-20.09" ],
              osPlaceholder: [ "ubuntu-latest", "macos-latest" ]
            };

            var matrixOverride = JSON.parse(process.env.MATRIX_OVERRIDE);
            console.log("matrixOverride:", matrixOverride);

            var matrix = { ...defaultMatrix };

            function expandEntryKeys(entry, keys, startPos) {
              for (let i = startPos; i < keys.length; ++i) {
                const key = keys[i];
                const value = entry[key];
                if (Array.isArray(value)) {
                  return value.flatMap(x => expandEntryKeys({ ...entry, [key]: x }, keys, i + 1));
                }
              }
              return [entry];
            }

            function expandEntry(entry) {
              return expandEntryKeys(entry, Object.keys(entry), 0);
            }

            function addToMatrix(entry) {
              const fullEntry = { ...defaultMatrix, ...entry };
              matrix.include = (matrix.include || []).concat(expandEntry(fullEntry));
            }

            addToMatrix({
              source: { repo: "sigprof/qmk_firmware", ref: "nix-shell-updates" },
              extra: "extraValue"
            });

            if (matrixOverride) {
              const overrideEntry = { ...defaultMatrix, ...matrixOverride };
              matrix = expandEntry(overrideEntry);
            }

            return matrix;

  dump:
    name: Dump
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Report data
        env:
          DATA: ${{ needs.setup.outputs.matrix }}
        run: |
          printf '%s' "$DATA" | jq

  #un:
  # name: Run
  # needs: setup
  # runs-on: ubuntu-latest
  # strategy:
  #   matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
  # steps:
  #   - name: Report matrix value
  #     env:
  #       DATA: ${{ toJSON(matrix) }}
  #     run: |
  #       printf '%s' "$DATA" | jq

  #ain:
  # name: Main job
  # needs: init
  # strategy:
  #   matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
  # runs-on: ${{ matrix.os }}
  # steps:
  #   - name: Report matrix values
  #     run: |
  #       echo "Repo: ${{ matrix.source.repo }}"
  #       echo "Ref:  ${{ matrix.source.ref  }}"
  #       echo "nixPath: ${{ matrix.nixPath }}"

