name: Test2
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        channel:
          - flake
          - nixos-unstable
          - nixos-22.05
        os:
          - system: x86_64-linux
            runs_on: ubuntu-latest
          - system: x86_64-darwin
            runs_on: macos-latest
    runs-on: ${{ matrix.os.runs_on }}
    steps:
      - name: Report matrix value
        env:
          DATA: ${{ toJSON(matrix) }}
        run: |
          printf '%s' "$DATA" | jq
