name: Test
on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository to test
        required: false
      ref:
        description: Branch or tag to test
        required: false
      os:
        description: OS to test
        required: false

jobs:
  init:
    name: Initialize the workflow
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.init.outputs.result }}
    steps:
      - id: init
        name: Prepare the matrix
        uses: actions/github-script@v4.0.2
        with:
          script: |
            const defaultMatrix = {
              "source": [
                { "repo": "qmk/qmk_firmware", "ref": "master" },
                { "repo": "qmk/qmk_firmware", "ref": "develop" },
              ],
              "nixPath": [ "nixpkgs=channel:nixos-20.09" ],
              "os": [ "ubuntu-latest", "macos-latest" ]
            };
            var matrix = { ...defaultMatrix };
            (matrix.include ??= []).push({
              source: { repo: "sigprof/qmk_firmware", ref: "nix-shell-updates" }
            });
            return matrix;

  dump:
    name: Dump
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Report data
        env:
          DATA: ${{ needs.init.outputs.matrix }}
        run: |
          printf '%s' "$DATA" | jq

  #ain:
  # name: Main job
  # needs: init
  # strategy:
  #   matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
  # runs-on: ${{ matrix.os }}
  # steps:
  #   - name: Report matrix values
  #     run: |
  #       echo "Repo: ${{ matrix.source.repo }}"
  #       echo "Ref:  ${{ matrix.source.ref  }}"
  #       echo "nixPath: ${{ matrix.nixPath }}"

