name: Test2
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - system: x86_64-linux
            runs_on: ubuntu-latest
          - system: x86_64-darwin
            runs_on: macos-latest
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo 'os: ${{ matrix.os }}'
        echo 'os.system: ${{ matrix.os.system }}'
        echo 'os.runs_on: ${{ matrix.os.runs_on }}'
