name: Test2
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        #os:
        #  - system: x86_64-linux
        #    runs_on: ubuntu-latest
        #  - system: x86_64-darwin
        #    runs_on: macos-latest
        test:
          - value1
    runs-on: ubuntu-latest
    steps:
      - name: Debug print
        run: |
        echo 'test = ${{ matrix.test }}'

