name: Test
on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository to test
        required: false
      ref:
        description: Branch or tag to test
        required: false
      os:
        description: OS to test
        required: false

jobs:
  init:
    name: Initialize the workflow
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.init.outputs.result }}
    steps:
      - id: init
        name: Prepare the matrix
        uses: actions/github-script@v4.0.2
        with:
          script: |
            return {
              "source": [
                { "repo": "qmk/qmk_firmware", "ref": "master" },
                { "repo": "qmk/qmk_firmware", "ref": "develop" },
                { "repo": "sigprof/qmk_firmware", "ref": "nix-shell-updates" },
              ],
              "os": [ "ubuntu-latest" ]
            };

  main:
    name: Main job
    needs: init
    strategy:
      matrix: ${{ needs.init.outputs.matrix }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Report matrix values
        run: |
          echo "Repo: ${{ matrix.source.repo }}"
          echo "Ref:  ${{ matrix.source.ref  }}"

